# Generated by Django 5.1.7 on 2025-04-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
