# Generated by Django 5.1.7 on 2025-04-05 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_chefprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='my_app.chefprofile'),
        ),
        migrations.AlterField(
            model_name='chefprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/userprof.avif', upload_to='profile_pics/'),
        ),
    ]
