# Generated by Django 5.1.7 on 2025-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_useraccount_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', to='my_app.recipe'),
        ),
    ]
