# Generated by Django 5.1.7 on 2025-04-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/userprof.avif', upload_to='profile_pics/'),
        ),
    ]
