# Generated by Django 5.1.7 on 2025-04-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_alter_useraccount_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='password',
        ),
    ]
