# Generated by Django 5.1.7 on 2025-04-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_remove_useraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('chef', 'Chef')], default='user', max_length=10),
        ),
    ]
