# Generated by Django 5.1.7 on 2025-04-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_useraccount_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
