# Generated by Django 5.1.7 on 2025-04-06 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_remove_useraccount_email_remove_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='my_app.chefprofile'),
        ),
    ]
