# Generated by Django 5.1.7 on 2025-04-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_recipe_chef'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='my_app.useraccount'),
        ),
        migrations.DeleteModel(
            name='ChefProfile',
        ),
    ]
